# Generated by Django 4.0.4 on 2022-07-17 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=250)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('name_en', models.CharField(default='', max_length=40, null=True)),
                ('name_ru', models.CharField(default='', max_length=40, null=True)),
                ('name_es', models.CharField(default='', max_length=40, null=True)),
                ('name_fr', models.CharField(default='', max_length=40, null=True)),
                ('name_he', models.CharField(default='', max_length=40, null=True)),
                ('code', models.CharField(default='', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('title_en', models.CharField(default='', max_length=200, null=True)),
                ('title_ru', models.CharField(default='', max_length=200, null=True)),
                ('title_es', models.CharField(default='', max_length=200, null=True)),
                ('title_fr', models.CharField(default='', max_length=200, null=True)),
                ('title_he', models.CharField(default='', max_length=200, null=True)),
                ('answer', models.TextField(null=True)),
                ('answer_en', models.TextField(null=True)),
                ('answer_ru', models.TextField(null=True)),
                ('answer_es', models.TextField(null=True)),
                ('answer_fr', models.TextField(null=True)),
                ('answer_he', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[

            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('name_en', models.CharField(default='', max_length=200, null=True)),
                ('name_ru', models.CharField(default='', max_length=200, null=True)),
                ('name_es', models.CharField(default='', max_length=200, null=True)),
                ('name_fr', models.CharField(default='', max_length=200, null=True)),
                ('name_he', models.CharField(default='', max_length=200, null=True)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('description_es', models.TextField(null=True)),
                ('description_fr', models.TextField(null=True)),
                ('description_he', models.TextField(null=True)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.currency')),

            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('name_en', models.CharField(default='', max_length=200, null=True)),
                ('name_ru', models.CharField(default='', max_length=200, null=True)),
                ('name_es', models.CharField(default='', max_length=200, null=True)),
                ('name_fr', models.CharField(default='', max_length=200, null=True)),
                ('name_he', models.CharField(default='', max_length=200, null=True)),
                ('slug', models.SlugField(default='')),
                ('multi_plane', models.BooleanField(default=False)),
                ('description', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('description_es', models.TextField(null=True)),
                ('description_fr', models.TextField(null=True)),
                ('description_he', models.TextField(null=True)),
                ('background_color', models.CharField(max_length=12)),
                ('icon', models.FileField(blank=True, default=None, null=True, upload_to='media/products/')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('name_en', models.CharField(default='', max_length=200, null=True)),
                ('name_ru', models.CharField(default='', max_length=200, null=True)),
                ('name_es', models.CharField(default='', max_length=200, null=True)),
                ('name_fr', models.CharField(default='', max_length=200, null=True)),
                ('name_he', models.CharField(default='', max_length=200, null=True)),
                ('count', models.IntegerField()),
                ('slug', models.SlugField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('order_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_name', models.CharField(max_length=250, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(1, 'being processed'), (2, 'done'), (3, 'canceled')], default=1)),
                ('offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.offer')),
                ('payment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.paymenttype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=250, null=True)),
                ('date_create', models.DateTimeField()),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='SupportTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('email', models.EmailField(default='', max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product'),
        ),
        migrations.AddField(
            model_name='offer',
            name='rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.rate'),
        ),
    ]
