# Generated by Django 4.0.4 on 2022-07-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='pay_type',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('crypto', 'Crypto Wallet')], default=12312, max_length=255),
            preserve_default=False,
        ),
    ]
