# Generated by Django 4.0.4 on 2022-07-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='id',
            field=models.BigAutoField(auto_created=True, default=123, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feature',
            name='name',
            field=models.TextField(null=True, verbose_name='product features'),
        ),
        migrations.AddField(
            model_name='feature',
            name='name_en',
            field=models.TextField(null=True, verbose_name='product features'),
        ),
        migrations.AddField(
            model_name='feature',
            name='name_es',
            field=models.TextField(null=True, verbose_name='product features'),
        ),
        migrations.AddField(
            model_name='feature',
            name='name_fr',
            field=models.TextField(null=True, verbose_name='product features'),
        ),
        migrations.AddField(
            model_name='feature',
            name='name_he',
            field=models.TextField(null=True, verbose_name='product features'),
        ),
        migrations.AddField(
            model_name='feature',
            name='name_ru',
            field=models.TextField(null=True, verbose_name='product features'),
        ),
    ]
