# Generated by Django 4.0.4 on 2022-07-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_feature_id_feature_name_feature_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='features',
            field=models.ManyToManyField(to='main.feature'),
        ),
    ]
