# Generated by Django 4.0.4 on 2022-07-22 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_transaction_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
