# Generated by Django 4.0.4 on 2022-07-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_customuser_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='google_access_token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
