# Generated by Django 4.0.4 on 2022-07-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_verified_customuser_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sing_in_social',
            field=models.BooleanField(default=False),
        ),
    ]
