# Generated by Django 4.0.4 on 2022-07-22 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_customuser_sing_in_social'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='sing_in_social',
            new_name='social_sign_up',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='google_access_token',
        ),
    ]
