# Generated by Django 4.0.4 on 2022-07-23 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_sing_in_social_customuser_social_sign_up_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='status',
        ),
    ]
