# Generated by Django 4.0.4 on 2022-07-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='service_password',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
    ]
