# Generated by Django 4.0.4 on 2022-08-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_subscription_communication_preferences_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supporttask',
            old_name='text',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='supporttask',
            name='title',
        ),
        migrations.RemoveField(
            model_name='supporttask',
            name='user',
        ),
        migrations.AddField(
            model_name='supporttask',
            name='img',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='communication_preferences',
            field=models.CharField(choices=[('email', 'Email'), ('wa', 'Whatsapp')], default='email', max_length=250),
        ),
    ]
