# Generated by Django 4.0.4 on 2022-08-08 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_supporttask_email_alter_supporttask_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockchain_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='currency',
            name='crypto',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CryptoWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paycode', models.CharField(max_length=250)),
                ('blockchain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallets', to='main.blockchain')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crypto_wallets', to='main.currency')),
            ],
        ),
    ]
