# Generated by Django 4.0.4 on 2022-08-12 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_blockchain_currency_crypto_cryptowallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
